version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stack-builder-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - stack-builder-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stack-builder-frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - stack-builder-network
    restart: unless-stopped

networks:
  stack-builder-network:
    driver: bridge
