name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        if: hashFiles('backend/Dockerfile') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            gaskony/ignition-stack-builder-backend:latest
            gaskony/ignition-stack-builder-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        if: hashFiles('frontend/Dockerfile') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            gaskony/ignition-stack-builder-frontend:latest
            gaskony/ignition-stack-builder-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify build success
        if: success()
        run: |
          echo "✅ Docker images built and pushed successfully"
          echo "Backend: gaskony/ignition-stack-builder-backend:latest"
          echo "Frontend: gaskony/ignition-stack-builder-frontend:latest"
          echo "Version: ${{ github.sha }}"
          echo ""
          echo "To deploy on any server, run:"
          echo "  cd /git/ignition-stack-builder"
          echo "  git pull origin main"
          echo "  ./scripts/deploy.sh"
